"""Grade a student's hand-drawn graph by sending both the reference and the
student's drawing to Gemini vision for comparison.

The Gemini prompt is structured to evaluate:
  - Curve shape and position vs. the reference
  - Vertical asymptotes (correct x-values, drawn as vertical lines)
  - Tangent line (correct slope and position)
  - Labeled points (correct placement)
  - Overall accuracy
"""
import asyncio
import base64
import json
import logging

from google.genai import types

from core.config import settings

from .graph_renderer import render_reference_graph
from .llm import _gemini_client

log = logging.getLogger(__name__)

_GRAPH_GRADE_PROMPT = """\
You are a math teacher evaluating a student's hand-drawn graph.

EXERCISE: {exercise_text}

REFERENCE GRAPH IMAGE: This is the correct graph generated by the computer. \
It shows the function curve (blue), vertical asymptotes (red dashed lines), \
the tangent line (green), and key points (orange dots).

STUDENT'S DRAWING IMAGE: This is what the student drew by hand.

Compare the student's drawing to the reference graph. Evaluate:
1. CURVE SHAPE: Does the student's curve match the reference? Check direction, \
 curvature, behavior near asymptotes, and general shape.
2. ASYMPTOTES: Are the vertical asymptotes drawn at the correct x-values?
3. TANGENT LINE: If a tangent is shown, does it have the correct slope and position?
4. LABELED POINTS: Are key points (like the origin or intersection points) marked correctly?
5. OVERALL: How accurate is the drawing overall?

Respond with ONLY valid JSON (no markdown, no code fences) in this exact format:
{{
  "score": <number 0-100>,
  "curve_correct": <true/false>,
  "asymptotes_correct": <true/false>,
  "tangent_correct": <true/null>,
  "points_correct": <true/false>,
  "feedback": "<1-3 sentence summary of what's right and wrong>",
  "suggestions": ["<specific suggestion 1>", "<specific suggestion 2>"]
}}

Rules:
- score: 100 = perfect, 80+ = good with minor issues, 60-79 = acceptable with noticeable errors, below 60 = needs significant improvement
- curve_correct: true if the general shape and direction match, even with minor imprecision
- tangent_correct: null if no tangent is required/shown
- suggestions: max 3 specific, actionable tips
- Be fair: hand-drawing is imprecise, so small deviations are OK. Flag only significant errors."""


def _decode_thumb(thumb: str) -> bytes:
    """Decode a data-URL thumbnail (data:image/png;base64,...) to raw PNG bytes."""
    if thumb.startswith("data:"):
        # Strip "data:image/png;base64," prefix
        _, rest = thumb.split(",", 1)
        return base64.b64decode(rest)
    # Assume raw base64
    return base64.b64decode(thumb)


async def grade_graph(
    graph: dict,
    function_expr: str,
    exercise_text: str,
    student_thumb: str,
) -> dict | None:
    """Compare a student's hand-drawn graph against the reference using Gemini vision.

    Parameters
    ----------
    graph : dict
        Reference graph spec from ``_build_graph``.
    function_expr : str
        The function expression string (e.g. ``ln((x+3)/(x-3))``).
    exercise_text : str
        The full exercise prompt shown to the student.
    student_thumb : str
        Base64 data-URL PNG of the student's drawing.

    Returns
    -------
    dict or None
        Grading result with score, per-element verdicts, feedback, suggestions.
        Returns None on Gemini failure.
    """
    ref_png = render_reference_graph(graph, function_expr)
    student_png = _decode_thumb(student_thumb)

    prompt = _GRAPH_GRADE_PROMPT.format(exercise_text=exercise_text)

    model = settings.gemini_vision_model or settings.gemini_model
    try:
        resp = await asyncio.wait_for(
            _gemini_client().aio.models.generate_content(
                model=model,
                contents=[
                    types.Part(text=prompt),
                    types.Part(inline_data=types.Blob(mime_type="image/png", data=ref_png)),
                    types.Part(inline_data=types.Blob(mime_type="image/png", data=student_png)),
                ],
                config=types.GenerateContentConfig(response_mime_type="application/json"),
            ),
            timeout=settings.gemini_timeout_seconds,
        )
        result = json.loads(resp.text)
        # Normalize
        result.setdefault("score", 0)
        result.setdefault("curve_correct", False)
        result.setdefault("asymptotes_correct", False)
        result.setdefault("tangent_correct", None)
        result.setdefault("points_correct", False)
        result.setdefault("feedback", "")
        result.setdefault("suggestions", [])
        return result
    except Exception as exc:
        log.warning("graph grading Gemini call failed: %s", exc)
        return None
