"""widen attempts.reason to text

Revision ID: d9a97322172e
Revises: a0192e01dd4d
Create Date: 2026-08-14 14:25:14.369427

"""
from alembic import op
import sqlalchemy as sa


revision = 'd9a97322172e'
down_revision = 'a0192e01dd4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attempts', 'reason',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attempts', 'reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
