"""Grade a student's hand-drawn graph by sending both the reference and the
student's drawing to Gemini vision for comparison.

The Gemini prompt is structured to evaluate:
  - Curve shape and position vs. the reference
  - Vertical asymptotes (correct x-values, drawn as vertical lines)
  - Tangent line (correct slope and position)
  - Labeled points (correct placement)
  - Overall accuracy
"""
import asyncio
import base64
import json
import logging

from google.genai import types

import time
from cache import get_system_model_settings
from ...pricing import record_api_usage

from core.config import settings

from ...llm import _gemini_client
from .graph_renderer import render_reference_graph

log = logging.getLogger(__name__)

_GRAPH_GRADE_PROMPT = """\
You are a math teacher evaluating a student's hand-drawn graph.

EXERCISE: {exercise_text}

REFERENCE GRAPH IMAGE: This is the correct graph generated by the computer. \
The function curve, asymptotes, tangent lines, and points are shown.

STUDENT DRAWING IMAGE: This is the student's attempt drawn on a canvas.

Evaluate whether the student correctly drew:
1. The curve: does it follow the correct shape, increasing/decreasing intervals, and approach the asymptotes properly?
2. Vertical asymptotes: did they draw dashed/solid vertical lines at the correct x positions?
3. Oblique/horizontal asymptotes: did they draw the correct asymptote lines?
4. Tangent lines: if requested, did they draw a tangent line at the specified point?
5. Special points: did they plot points like extrema, intercepts, or given points?

Be lenient with drawing precision — hand-drawn curves on a tablet/screen are imperfect. \
Focus on mathematical correctness: general shape, correct quadrant, correct asymptotes, \
proper monotonic behavior.

Respond with a JSON object matching this schema:
{{
  "score": <integer 0-100>,
  "curve_correct": <boolean>,
  "asymptotes_correct": <boolean>,
  "tangent_correct": <boolean or null if not applicable>,
  "points_correct": <boolean or null if not applicable>,
  "feedback": "<1-2 sentences in Khmer explaining what was good and what was missed>",
  "suggestions": ["<actionable tip 1>", "<actionable tip 2>"]
}}
"""


def _decode_thumb(data_uri: str) -> bytes:
    """Decode a data:image/png;base64,... URI to raw bytes."""
    if "," in data_uri:
        data_uri = data_uri.split(",", 1)[1]
    return base64.b64decode(data_uri)


async def grade_student_graph(
    exercise_text: str,
    graph: dict,
    function_expr: str,
    student_thumb: str,
    user_id: any = None,
) -> dict | None:
    """Compare a student's hand-drawn graph against the reference using Gemini vision.

    Args:
        exercise_text: Problem prompt in Khmer/English
        graph: The graph spec from the exercise JSON
        function_expr: SymPy expression string for the function
        student_thumb: Base64 data-URI of the student's canvas drawing
        user_id: Optional UUID of the student for usage cost tracking

    Returns:
        Grading result with score, per-element verdicts, feedback, suggestions.
        Returns None on Gemini failure.
    """
    ref_png = render_reference_graph(graph, function_expr)
    student_png = _decode_thumb(student_thumb)

    prompt = _GRAPH_GRADE_PROMPT.format(exercise_text=exercise_text)

    sys_models = await get_system_model_settings()
    model = sys_models.get("vision_model") or settings.gemini_vision_model or settings.gemini_model

    t0 = time.perf_counter()
    try:
        resp = await asyncio.wait_for(
            _gemini_client().aio.models.generate_content(
                model=model,
                contents=[
                    types.Part(text=prompt),
                    types.Part(inline_data=types.Blob(mime_type="image/png", data=ref_png)),
                    types.Part(inline_data=types.Blob(mime_type="image/png", data=student_png)),
                ],
                config=types.GenerateContentConfig(response_mime_type="application/json"),
            ),
            timeout=settings.gemini_timeout_seconds,
        )
        latency_ms = int((time.perf_counter() - t0) * 1000)

        prompt_tokens = 0
        completion_tokens = 0
        if hasattr(resp, "usage_metadata") and resp.usage_metadata:
            prompt_tokens = getattr(resp.usage_metadata, "prompt_token_count", 0) or 0
            completion_tokens = getattr(resp.usage_metadata, "candidates_token_count", 0) or 0
        else:
            prompt_tokens = 516 + (len(prompt) // 4)
            completion_tokens = len(resp.text or "") // 4

        record_api_usage(
            user_id=user_id,
            endpoint="graph_grade",
            provider="gemini",
            model_name=model,
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            latency_ms=latency_ms,
            success=True,
        )

        result = json.loads(resp.text)
        # Normalize
        result.setdefault("score", 0)
        result.setdefault("curve_correct", False)
        result.setdefault("asymptotes_correct", False)
        result.setdefault("tangent_correct", None)
        result.setdefault("points_correct", False)
        result.setdefault("feedback", "")
        result.setdefault("suggestions", [])
        return result
    except Exception as exc:
        latency_ms = int((time.perf_counter() - t0) * 1000)
        record_api_usage(
            user_id=user_id,
            endpoint="graph_grade",
            provider="gemini",
            model_name=model,
            prompt_tokens=516 + (len(prompt) // 4),
            completion_tokens=0,
            latency_ms=latency_ms,
            success=False,
            error_message=str(exc),
        )
        log.warning("graph grading Gemini call failed: %s", exc)
        return None
